### NBA Season Totals

In [1]:
# load the necessary packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# This imports the client
from basketball_reference_web_scraper import client

In [2]:
#Get data for all NBA players
def load_data(year):
    data = client.players_season_totals(season_end_year=year)
    nba = pd.DataFrame(data=data, index=None)
    return nba

In [3]:
#NBA players statistics per year
nba_data = load_data(2022)
nba_data.head(10)

,slug,name,positions,age,team,games_played,games_started,minutes_played,made_field_goals,attempted_field_goals,...,made_free_throws,attempted_free_throws,offensive_rebounds,defensive_rebounds,assists,steals,blocks,turnovers,personal_fouls,points
0,achiupr01,Precious Achiuwa,[Position.CENTER],22.0,Team.TORONTO_RAPTORS,22,17,579,79,196,...,19,36,49,129,33,12,12,25,54,185
1,adamsst01,Steven Adams,[Position.CENTER],28.0,Team.MEMPHIS_GRIZZLIES,36,36,917,94,176,...,64,102,147,178,104,32,19,58,59,252
2,adebaba01,Bam Adebayo,[Position.CENTER],24.0,Team.MIAMI_HEAT,18,18,592,126,243,...,85,112,49,134,57,20,6,53,59,337
3,aldamsa01,Santi Aldama,[Position.POWER_FORWARD],21.0,Team.MEMPHIS_GRIZZLIES,16,0,156,24,66,...,7,12,16,26,12,2,3,5,17,58
4,aldrila01,LaMarcus Aldridge,[Position.CENTER],36.0,Team.BROOKLYN_NETS,25,8,590,149,260,...,40,48,35,107,23,10,29,19,42,349
5,alexani01,Nickeil Alexander-Walker,[Position.SHOOTING_GUARD],23.0,Team.NEW_ORLEANS_PELICANS,32,18,902,166,446,...,42,57,32,89,86,31,11,50,59,443
6,allengr01,Grayson Allen,[Position.SHOOTING_GUARD],26.0,Team.MILWAUKEE_BUCKS,33,32,942,138,325,...,34,39,14,99,43,25,13,22,51,402
7,allenja01,Jarrett Allen,[Position.CENTER],23.0,Team.CLEVELAND_CAVALIERS,28,28,913,191,272,...,87,121,91,211,55,25,38,55,52,470
8,alvarjo01,Jose Alvarado,[Position.POINT_GUARD],23.0,Team.NEW_ORLEANS_PELICANS,8,0,41,5,13,...,2,3,2,3,9,4,0,1,3,14
9,anderju01,Justin Anderson,[Position.GUARD],28.0,Team.CLEVELAND_CAVALIERS,3,0,47,4,8,...,3,4,0,6,6,1,0,2,4,13

In [4]:
#Number of Rows
nba_data.shape[0]

563

In [5]:
#Look at columns
nba_data.columns

Index(['slug', 'name', 'positions', 'age', 'team', 'games_played',
       'games_started', 'minutes_played', 'made_field_goals',
       'attempted_field_goals', 'made_three_point_field_goals',
       'attempted_three_point_field_goals', 'made_free_throws',
       'attempted_free_throws', 'offensive_rebounds', 'defensive_rebounds',
       'assists', 'steals', 'blocks', 'turnovers', 'personal_fouls', 'points'],
      dtype='object')

In [6]:
nba_data.dtypes

slug                                  object
name                                  object
positions                             object
age                                  float64
team                                  object
games_played                           int64
games_started                          int64
minutes_played                         int64
made_field_goals                       int64
attempted_field_goals                  int64
made_three_point_field_goals           int64
attempted_three_point_field_goals      int64
made_free_throws                       int64
attempted_free_throws                  int64
offensive_rebounds                     int64
defensive_rebounds                     int64
assists                                int64
steals                                 int64
blocks                                 int64
turnovers                              int64
personal_fouls                         int64
points                                 int64
dtype: object

In [7]:
# Clean up Positions Column
positions_clean = nba_data['positions'].apply(lambda x: ''.join(map(str, x))).str.split(".", n = 1, expand = True)
nba_data['position'] = positions_clean[1]
nba_data.drop(columns =['positions'], inplace = True)

In [8]:
# Clean up team Column
a=lambda x: str(x).split('.')
team_clean = nba_data['team'].apply(a)
team_clean = team_clean.apply(lambda x: ','.join(map(str, x))).str.split(",", n = 1, expand = True)
nba_data['nba_team'] = team_clean[1]
nba_data.drop(columns =['team'], inplace = True)
nba_data.head()

,slug,name,age,games_played,games_started,minutes_played,made_field_goals,attempted_field_goals,made_three_point_field_goals,attempted_three_point_field_goals,...,offensive_rebounds,defensive_rebounds,assists,steals,blocks,turnovers,personal_fouls,points,position,nba_team
0,achiupr01,Precious Achiuwa,22.0,22,17,579,79,196,8,28,...,49,129,33,12,12,25,54,185,CENTER,TORONTO_RAPTORS
1,adamsst01,Steven Adams,28.0,36,36,917,94,176,0,0,...,147,178,104,32,19,58,59,252,CENTER,MEMPHIS_GRIZZLIES
2,adebaba01,Bam Adebayo,24.0,18,18,592,126,243,0,1,...,49,134,57,20,6,53,59,337,CENTER,MIAMI_HEAT
3,aldamsa01,Santi Aldama,21.0,16,0,156,24,66,3,27,...,16,26,12,2,3,5,17,58,POWER_FORWARD,MEMPHIS_GRIZZLIES
4,aldrila01,LaMarcus Aldridge,36.0,25,8,590,149,260,11,30,...,35,107,23,10,29,19,42,349,CENTER,BROOKLYN_NETS

In [9]:
# Duplicate rows due to this player changing teams
nba_data[nba_data['name'] == 'Gary Harris']

,slug,name,age,games_played,games_started,minutes_played,made_field_goals,attempted_field_goals,made_three_point_field_goals,attempted_three_point_field_goals,...,offensive_rebounds,defensive_rebounds,assists,steals,blocks,turnovers,personal_fouls,points,position,nba_team
203,harriga01,Gary Harris,27.0,28,18,787,106,238,38,110,...,22,45,55,19,5,32,51,288,SHOOTING_GUARD,ORLANDO_MAGIC

In [10]:
#Format data using SQL
from pandasql import sqldf

query = """
        SELECT
            slug,
            name,
            position,
            SUM(games_played) AS games_played,
            SUM(games_started) AS games_started,
            SUM(minutes_played) AS minutes_played,
            SUM(made_field_goals) AS made_field_goals,
            SUM(attempted_field_goals) AS attempted_field_goals,
            SUM(made_three_point_field_goals) AS made_three_point_field_goals,
            SUM(attempted_three_point_field_goals) AS attempted_three_point_field_goals,
            SUM(made_free_throws) AS made_free_throws,
            SUM(attempted_free_throws) AS attempted_free_throws,
            SUM(offensive_rebounds) AS offensive_rebounds,
            SUM(defensive_rebounds) AS defensive_rebounds,
            SUM(assists) AS assists,
            SUM(steals) AS steals,
            SUM(blocks) AS blocks,
            SUM(turnovers) AS turnovers,
            SUM(personal_fouls) AS personal_fouls,
            SUM(points) AS points
        FROM nba_data
        GROUP BY 1,2,3

"""



nba_data_cleaned = sqldf(query, locals())

In [11]:
nba_data_cleaned.head()

,slug,name,position,games_played,games_started,minutes_played,made_field_goals,attempted_field_goals,made_three_point_field_goals,attempted_three_point_field_goals,made_free_throws,attempted_free_throws,offensive_rebounds,defensive_rebounds,assists,steals,blocks,turnovers,personal_fouls,points
0,achiupr01,Precious Achiuwa,CENTER,22,17,579,79,196,8,28,19,36,49,129,33,12,12,25,54,185
1,adamsst01,Steven Adams,CENTER,36,36,917,94,176,0,0,64,102,147,178,104,32,19,58,59,252
2,adebaba01,Bam Adebayo,CENTER,18,18,592,126,243,0,1,85,112,49,134,57,20,6,53,59,337
3,aldamsa01,Santi Aldama,POWER_FORWARD,16,0,156,24,66,3,27,7,12,16,26,12,2,3,5,17,58
4,aldrila01,LaMarcus Aldridge,CENTER,25,8,590,149,260,11,30,40,48,35,107,23,10,29,19,42,349

In [12]:
# Add other statistical measures. ie: PPG, RPG
nba_data_cleaned['MPG'] = round(nba_data_cleaned['minutes_played']/nba_data_cleaned['games_played'],1)
nba_data_cleaned['PPG'] = round(nba_data_cleaned['points']/nba_data_cleaned['games_played'],1)
nba_data_cleaned['RPG'] = round((nba_data_cleaned['offensive_rebounds'] + nba_data_cleaned['defensive_rebounds'])/nba_data_cleaned['games_played'],1)
nba_data_cleaned['APG'] = round(nba_data_cleaned['assists']/nba_data_cleaned['games_played'],1)
nba_data_cleaned['FG%'] = round(nba_data_cleaned['made_field_goals']/nba_data_cleaned['attempted_field_goals'],3)
nba_data_cleaned['FT'] = round(nba_data_cleaned['made_free_throws']/nba_data_cleaned['games_played'],1)
nba_data_cleaned['FT%'] = round(nba_data_cleaned['made_free_throws']/nba_data_cleaned['attempted_free_throws'],3)
nba_data_cleaned['3P'] = round(nba_data_cleaned['made_three_point_field_goals']/nba_data_cleaned['games_played'],1)
nba_data_cleaned['3P%'] = round(nba_data_cleaned['made_three_point_field_goals']/nba_data_cleaned['attempted_three_point_field_goals'],1)
nba_data_cleaned['STPG'] = round(nba_data_cleaned['steals']/nba_data_cleaned['games_played'],1)
nba_data_cleaned['BLKPG'] = round(nba_data_cleaned['blocks']/nba_data_cleaned['games_played'],1)
nba_data_cleaned['TOPG'] = round(nba_data_cleaned['turnovers']/nba_data_cleaned['games_played'],1)
nba_data_cleaned = nba_data_cleaned.fillna(0)

In [13]:
# New dataframe with most important information for Fantasy
nba_dataset = nba_data_cleaned[['name', 'games_played', 'PPG', 'FG%', 'FT', 'FT%', '3P', '3P%', 'RPG', 'APG', 'STPG', 'BLKPG', 'TOPG']]
nba_dataset.head()

,name,games_played,PPG,FG%,FT,FT%,3P,3P%,RPG,APG,STPG,BLKPG,TOPG
0,Precious Achiuwa,22,8.4,0.403,0.9,0.528,0.4,0.3,8.1,1.5,0.5,0.5,1.1
1,Steven Adams,36,7.0,0.534,1.8,0.627,0.0,0.0,9.0,2.9,0.9,0.5,1.6
2,Bam Adebayo,18,18.7,0.519,4.7,0.759,0.0,0.0,10.2,3.2,1.1,0.3,2.9
3,Santi Aldama,16,3.6,0.364,0.4,0.583,0.2,0.1,2.6,0.8,0.1,0.2,0.3
4,LaMarcus Aldridge,25,14.0,0.573,1.6,0.833,0.4,0.4,5.7,0.9,0.4,1.2,0.8

### Game Logs

In [14]:
pip install basketball-reference-scraper

Requirement already satisfied: basketball-reference-scraper in /Users/abdirahmanali/.pyenv/versions/3.7.3/lib/python3.7/site-packages (1.0.29)
Requirement already satisfied: six==1.13.0 in /Users/abdirahmanali/.pyenv/versions/3.7.3/lib/python3.7/site-packages (from basketball-reference-scraper) (1.13.0)
Requirement already satisfied: pandas==1.3.1 in /Users/abdirahmanali/.pyenv/versions/3.7.3/lib/python3.7/site-packages (from basketball-reference-scraper) (1.3.1)
Requirement already satisfied: bs4==0.0.1 in /Users/abdirahmanali/.pyenv/versions/3.7.3/lib/python3.7/site-packages (from basketball-reference-scraper) (0.0.1)
Requirement already satisfied: requests==2.22.0 in /Users/abdirahmanali/.pyenv/versions/3.7.3/lib/python3.7/site-packages (from basketball-reference-scraper) (2.22.0)
Requirement already satisfied: beautifulsoup4==4.8.2 in /Users/abdirahmanali/.pyenv/versions/3.7.3/lib/python3.7/site-packages (from basketball-reference-scraper) (4.8.2)
Requirement already satisfied: numpy==1.18.1 in /Users/abdirahmanali/.pyenv/versions/3.7.3/lib/python3.7/site-packages (from basketball-reference-scraper) (1.18.1)
Requirement already satisfied: lxml==4.6.3 in /Users/abdirahmanali/.pyenv/versions/3.7.3/lib/python3.7/site-packages (from basketball-reference-scraper) (4.6.3)
Requirement already satisfied: python-dateutil==2.8.1 in /Users/abdirahmanali/.pyenv/versions/3.7.3/lib/python3.7/site-packages (from basketball-reference-scraper) (2.8.1)
Requirement already satisfied: pytz==2019.3 in /Users/abdirahmanali/.pyenv/versions/3.7.3/lib/python3.7/site-packages (from basketball-reference-scraper) (2019.3)
Requirement already satisfied: soupsieve==1.9.5 in /Users/abdirahmanali/.pyenv/versions/3.7.3/lib/python3.7/site-packages (from basketball-reference-scraper) (1.9.5)
Requirement already satisfied: idna<2.9,>=2.5 in /Users/abdirahmanali/.pyenv/versions/3.7.3/lib/python3.7/site-packages (from requests==2.22.0->basketball-reference-scraper) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/abdirahmanali/.pyenv/versions/3.7.3/lib/python3.7/site-packages (from requests==2.22.0->basketball-reference-scraper) (1.25.11)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/abdirahmanali/.pyenv/versions/3.7.3/lib/python3.7/site-packages (from requests==2.22.0->basketball-reference-scraper) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /Users/abdirahmanali/.pyenv/versions/3.7.3/lib/python3.7/site-packages (from requests==2.22.0->basketball-reference-scraper) (2020.6.20)
WARNING: You are using pip version 21.0.1; however, version 21.3.1 is available.
You should consider upgrading via the '/Users/abdirahmanali/.pyenv/versions/3.7.3/bin/python3.7 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [15]:
from basketball_reference_scraper.players import get_stats, get_game_logs, get_player_headshot

In [74]:
import json

#player_name, start_date, end_date, playoff=False
player_name = nba_data_cleaned['name'].tolist()
start_dates = '2021-10-01'
end_dates = '2022-05-01'

In [78]:
def get_game_logs(name, start_date, end_dates, playoffs):
    player_dict = [player for player in player_name if nba_data_cleaned['name'] == name]
    print(player_dict)

if __name__=="__main__":
    get_game_logs("Lebron James", "2021-10-01", "2022-05-31", "FALSE")

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().